// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Hub.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::mp3;

class HubHandler : virtual public HubIf {
 public:
  HubHandler() {
    // Your initialization goes here
  }

  void join(const int16_t port) {
    // Your implementation goes here
    printf("join\n");
  }

  void leave(const int16_t port) {
    // Your implementation goes here
    printf("leave\n");
  }

  void getMembers(std::vector<int16_t> & _return) {
    // Your implementation goes here
    printf("getMembers\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HubHandler> handler(new HubHandler());
  shared_ptr<TProcessor> processor(new HubProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

