/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hub_CONSTANTS_H
#define hub_CONSTANTS_H

#include "hub_types.h"

namespace mp3 {

class hubConstants {
 public:
  hubConstants();

};

extern const hubConstants g_hub_constants;

} // namespace

#endif
