/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hub_constants.h"

namespace mp3 {

const hubConstants g_hub_constants;

hubConstants::hubConstants() {
}

} // namespace

