/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "node_constants.h"

namespace mp3 {

const nodeConstants g_node_constants;

nodeConstants::nodeConstants() {
}

} // namespace

