/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef node_CONSTANTS_H
#define node_CONSTANTS_H

#include "node_types.h"

namespace mp3 {

class nodeConstants {
 public:
  nodeConstants();

};

extern const nodeConstants g_node_constants;

} // namespace

#endif
